version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "33060:3306"
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:3.2.6
    ports:
      - "63790:6379"
    command: redis-server --appendonly yes
    volumes:
       - redis-volume:/data
  web:
    build:
      context: .
      dockerfile: ./dockers/rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - ./vendor/bundle:/usr/local/bundle
      - bundle-volume:/usr/local/bundle
    environment:
      RAILS_ENV: development
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
    depends_on:
      - db
      - redis
volumes:
  db-volume:
    driver: local
  redis-volume:
    driver: local
  bundle-volume:
    driver: local